n1 = int(input("กรุณากรอกเลขจำนวนที่หนึ่ง :"))
n2 = int(input("กรุณากรอกเลขจำนวนที่สอง :"))
strF = str(n1)
strS = str(n2)
sum = n1 + n2
dif = n1 - n2
mul = n1 * n2
mod = n1 / n2
print(strF,"+", strS,"=",sum)
print(strF,"-", strS,"=",dif)
print(strF,"*", strS,"=",mul)
print(strF,"/", strS,"=",mod)